### ISSUE TITLE
[question] How to access stream settings when launching with arguments?

### ISSUE THREAD

**Issue by systox** [louis-bompart/louis-bompart.github.io#1]
Great guide, thanks for putting this together and hosting it. 

Question for anyone that might know:

Is there a way to change stream settings when launching a moonlight game directly with the launch arguments through "Game mode" on the steam deck? 

I noticed when I use the hotkeys "Start Select R1 L1" it just exits me out to the steamos home screen. But when i launch moonlight in game mode without the 'stream host game' argument, the button combination works as intended and i can change bitrate, etc. 

Thank you.

**Comment by louis-bompart** [comment]
Hey @systox , check-out https://github.com/moonlight-stream/moonlight-qt, I think you'll have more eyeballs on your question.

Overall, you can add any command line arguments in the steam shortcut, so if the option you want is available through command-line, you should be able to add them.
